### PR TITLE
Add Windows Support

### PR DESCRIPTION
**Pull request by acurless**
Support using the plugin on windows, as well as linux.
This involved the following
- On windows systems the command 'cmd /c' has to be prepended to the elm-make command
- Removed the reliance on the hardcoded '/' character for path separation. All paths are resolved using the File or Paths classes

### CODE REVIEW

**Comment by acurless** [comment]
Travis CI build failed due to a network issue, not sure how to rerun.

**Comment by tmohme** [comment]
I'm delighted to see that someone is actually using this plugin - and even more to see that you invested the time to contribute.
Please  have some patience as I'm currently pretty busy . . . it will probably take some time for me to have a detailed look at your pull request.

**Comment by tmohme** [comment]
As I haven't anticipated someone actually contributing, I was sloppy in not creating a contribution guide beforehand.
Now we have the a bit awkward situation that your contribution does not live up to my expectations.  
We have two options here:  
* you revisit your work - making your changes conform to the contribution guide
* I manually cherry-pick the few lines that contain the actual adaption to windows

**Comment by acurless** [comment]
I decided to go in a different direction and won't be using that plugin. You are welcome to cherry pick anything you feel useful, but I can put any more time into this. Thank you for your time reviewing.

**Pull request closed without merging**
